[package]
name = "pow-kit"
version = "0.1.0"
edition = "2024"
authors = ["Nugzari Uzoevi <nougzarm@icloud.com>"]
repository = "https://github.com/nougzarm/pow-kit"
categories = ["cryptography", "algorithms"]
keywords = ["proof-of-work", "framework"]

[dependencies]
